export const CREATE_BOOK_SUCCESSFUL = 'CREATE_BOOK_SUCCESSFUL';
export const CREATE_BOOK_PENDING = 'CREATE_BOOK_PENDING';
export const CREATE_BOOK_FAILURE = 'CREATE_BOOK_FAILURE';
export const READ_BOOKS_SUCCESSFUL = 'READ_BOOKS_SUCCESFUL';
export const READ_BOOKS_PENDING = 'READ_BOOKS_PENDING';
export const READ_BOOKS_FAILURE = 'READ_BOOKS_FAILURE';
export const UPDATE_BOOK_SUCCESSFUL = 'UPDATE_BOOK_SUCCESSFUL';
export const UPDATE_BOOK_PENDING = 'UPDATE_BOOK_PENDING';
export const UPDATE_BOOK_FAILURE = 'UPDATE_BOOK_FAILURE';
export const DELETE_BOOK_SUCCESSFUL = 'DELETE_BOOK_SUCCESSFUL';
export const DELETE_BOOK_PENDING = 'DELETE_BOOK_PENDING';
export const DELETE_BOOK_FAILURE = 'DELETE_BOOK_FAILURE';
export const RESET_BOOK_STATE = 'RESET_BOOK_STATE';

export const READ_AUTHORS_SUCCESSFUL = 'READ_AUTHORS_SUCCESSFUL';
export const READ_AUTHORS_PENDING = 'READ_AUTHORS_PENDING';
export const READ_AUTHORS_FAILURE = 'READ_AUTHORS_FAILURE';
export const RESET_AUTHOR_STATE = 'RESET_AUTHOR_STATE';